name: work_schedule_app
description: "Workforce scheduling and PTO management app."
publish_to: 'none'

version: 1.3.2+15

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi:
    git:
      url: https://github.com/tekartik/sqflite
      path: sqflite_common_ffi

  # Utilities
  path: ^1.8.3
  shared_preferences: ^2.2.2
  uuid: ^4.5.2

  # UI
  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  desktop_drop: ^0.5.0

  # PDF/Printing
  pdf: ^3.11.0
  printing: ^5.12.0
  http: ^1.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.7

flutter:
  uses-material-design: true
msix_config:
  display_name: Manager Schedule App
  publisher_display_name: Jason S
  identity_name: com.jasons.managerscheduleapp
  publisher: CN=Manager Schedule App, O=Jason S
  msix_version: 1.3.2.0
  logo_path: windows/runner/resources/app_icon.ico
  certificate_path: certs/ManagerScheduleApp.pfx
  capabilities: internetClient
  languages: en-us